
name: dogfood merge
# This workflow is triggered on pushes to master and dogfood branches
on:
  push:
    branches:
      - master
      - 'dogfood/**'
  delete:
    branches:
      - 'dogfood/**'
jobs:
  dogfood_merge:
    runs-on: ubuntu-latest
    name: Update dogfood branch
    steps:
    - name: git octopus step      
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      id: dogfood
      uses: SonarSource/gh-action_dogfood_merge@task/dr/BUILD-796-fix-delete-dogfood-branches
