on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Update dogfood branch
    steps:
    - name: git octopus step
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: dogfood
      uses: drautureau-sonarsource/gh-action_git-octopus@init
      with:
        dogfood-branch: 'dogfood-on-sonarcloud'
    # Use the output from the `dogfood` step
    - name: Get the name of the dogfood branch and its HEAD SHA1
      run: echo "The dogfood branch was ${{ steps.dogfood.outputs.dogfood-branch }} and its HEAD SHA1 was ${{ steps.dogfood.outputs.sha1 }}"
