on:
  workflow_dispatch:
  schedule:
    # At 01:00 on Monday
    - cron:  '0 1 * * 1'
name: Upgrade SQ plugin API
jobs:
  upgrade-sq-plugin-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code from master branch
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: master
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Rebase the branch 'check-update-of-sq-plugin-api' and upgrade SQ plugin API
        uses: ./.github/actions/upgrade-sq-plugin-api
        env:
          ARTIFACTORY_URL: https://repox.jfrog.io/artifactory
          ARTIFACTORY_PASSWORD: ${{ secrets.REPOX_API_KEY }}
          ARTIFACTORY_USERNAME: ${{ secrets.REPOX_LOGIN }}
